x-defaults: &defaults
  restart: unless-stopped
  depends_on:
      postgres:
        condition: service_healthy
      dragonfly:
        condition: service_healthy
  build: &build
    context: .
    dockerfile: Dockerfile
    args: &build-args
      DATABASE_URL: ${DATABASE_URL}
      TENDERMINT_URL: ${TENDERMINT_URL}
      CACHE_URL: ${CACHE_URL}
      WEBSERVER_PORT: ${WEBSERVER_PORT}
  environment: &env-vars
    <<: *build-args
  command: "./service \
    --tendermint-url ${TENDERMINT_URL} \
    --database-url ${DATABASE_URL}"
  extra_hosts:
  - "host.docker.internal:host-gateway"

include:
  - docker-compose-db.yml

services:
  chain:
    <<: *defaults
    image: namada/chain-indexer
    command: "./service \
      --tendermint-url ${TENDERMINT_URL} \
      --database-url ${DATABASE_URL} \
      --initial-query-retry-time=15"
    build:
      <<: *build
      args:
        <<: *build-args
        PACKAGE: chain

  governance:
    <<: *defaults
    image: namada/governance-indexer
    build:
      <<: *build
      args:
        <<: *build-args
        PACKAGE: governance

  pos:
    <<: *defaults
    image: namada/pos-indexer
    build:
      <<: *build
      args:
        <<: *build-args
        PACKAGE: pos

  rewards:
    <<: *defaults
    image: namada/rewards-indexer
    build:
      <<: *build
      args:
        <<: *build-args
        PACKAGE: rewards

  parameters:
    <<: *defaults
    image: namada/parameters-indexer
    build:
      <<: *build
      args:
        <<: *build-args
        PACKAGE: parameters

  transactions:
    <<: *defaults
    image: namada/transaction-indexer
    build:
      <<: *build
      args:
        <<: *build-args
        PACKAGE: transactions

  webserver:
    image: namada/webserver-indexer
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PACKAGE: webserver
    command: "./service"
    ports:
      - ${WEBSERVER_PORT}:5001
    environment:
      <<: *env-vars
    healthcheck:
      test: curl --fail http://localhost:5001/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

