x-defaults: &defaults
  restart: on-failure
  depends_on:
    - postgres
  build: &build
    context: .
    dockerfile: Dockerfile
    args: &build-args
      DATABASE_URL: ${DATABASE_URL}
      TENDERMINT_URL: ${TENDERMINT_URL}
      CHAIN_ID: ${CHAIN_ID}
      CACHE_URL: ${CACHE_URL}
      WEBSERVER_PORT: ${WEBSERVER_PORT}
  environment: &env-vars
    <<: *build-args
  command: "./service \
    --tendermint-url ${TENDERMINT_URL} \
    --database-url ${DATABASE_URL}"

include:
  - docker-compose-db.yml

services:
  chain:
    <<: *defaults
    image: namada/chain-indexer
    command: "./service \
      --tendermint-url ${TENDERMINT_URL} \
      --database-url ${DATABASE_URL} \
      --initial-query-retry-time=15"
    build:
      <<: *build
      args:
        <<: *build-args
        PACKAGE: chain

  governance:
    <<: *defaults
    image: namada/governance-indexer
    build:
      <<: *build
      args:
        <<: *build-args
        PACKAGE: governance

  pos:
    <<: *defaults
    image: namada/pos-indexer
    build:
      <<: *build
      args:
        <<: *build-args
        PACKAGE: pos

  rewards:
    <<: *defaults
    image: namada/rewards-indexer
    build:
      <<: *build
      args:
        <<: *build-args
        PACKAGE: rewards

  parameters:
    <<: *defaults
    image: namada/parameters-indexer
    build:
      <<: *build
      args:
        <<: *build-args
        PACKAGE: parameters

  transactions:
    <<: *defaults
    image: namada/transaction-indexer
    build:
      <<: *build
      args:
        <<: *build-args
        PACKAGE: transactions

  webserver:
    image: namada/webserver-indexer
    restart: on-failure
    depends_on:
      - postgres
      - dragonfly
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PACKAGE: webserver
    command: "./service"
    ports:
      - ${WEBSERVER_PORT}:5000
    environment:
      <<: *env-vars
    healthcheck:
      test: curl --fail http://localhost:5000/health || exit 1
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 10s
