[general]

host = "0.0.0.0"
port = 6543
admin_username = "postgres"
admin_password = "password"

enable_prometheus_exporter = false
prometheus_exporter_port = 9930

dns_cache_enabled = true
dns_max_ttl = 60

[pools.namada-indexer]
pool_mode = "session"
prepared_statements_cache_size = 500
query_parser_enabled = false
query_parser_read_write_splitting = false
idle_timeout = 300
connect_timeout = 10

[pools.namada-indexer.users.0]
username = "postgres"
password = "password"
pool_size = 50
min_pool_size = 5

[pools.namada-indexer.shards.0]
servers = [
  ["postgres", 5433, "primary"]
]
database = "namada-indexer"